# common
random_state: 42

# data
dataset_path: .
dataset_output_path: ./dataset
training_dataset_path: ./dataset
imsize: (224, 224)

# training
model: resnet50
epochs: 20
batch_size: 16
lr: 0.001
num_workers: 8