# common
random_state: 42

# clearml
project_name: ASL_recognition
dataset_name: ASL
dataset_id: 4f15d3acaec34093b3dc51f42cdf2539

# data
dataset_path: .
dataset_output_path: ./dataset
training_dataset_path: ./dataset
imsize: [224, 224]
class_num: 5

# training
model: resnet50
epochs: 2
batch_size: 16
lr: 0.001
num_workers: 4