# common
random_state: 42

# clearml
project_name: ASL_recognition
dataset_name: ASL_raw
training_dataset_name: ASL

# data
imsize: [224, 224]
dataset_split_ratio: [.7, .2, .1]
class_num: 29

# training
model: resnet50
epochs: 2
batch_size: 64
lr: 0.001
num_workers: 4
log_every: 100