name: auto-format

on:
  [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.14
          architecture: x64
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install flake8
        run: pip install flake8
      - name: Run flake8
        run: flake8 . --max-line-length 99